### ISSUE TITLE
UnhandledPromiseRejectionWarning when calling with --user

### ISSUE THREAD

**Issue by jeffbyrnes** [mheap/github-default-branch#15]
I’m running into some sort of API error, but it’s difficult to tell what’s going on, and `--verbose` doesn’t seem to offer much in the way of debug messages. Based on the stack, it appears to be coming from `bin/github-default-branch:64`, so it might not be your code that’s causing it.

https://github.com/mheap/github-default-branch/blob/9dda05402739e03265fc972dd37a669b272872d1/bin/github-default-branch#L64

```bash
12:22:53 (0) jeffbyrnes at Jeff’s iMac in ~/dev/dotfiles on main
♠ github-default-branch --verbose --user jeffbyrnes
? This tool will:
* Create a new branch (main) at the same commit as master
* Update all pull requests that pointed at master to main
* Replace master with main in README.md
* DELETE THE OLD BRANCH (master). Run again with --keep-old to skip this step
Continue? Yes
You have 4981 API requests remaining

(node:89229) UnhandledPromiseRejectionWarning: HttpError: Server Error
    at /usr/local/lib/node_modules/github-default-branch/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/usr/local/lib/node_modules/github-default-branch/src/get-repos.js:19:13)
    at async /usr/local/lib/node_modules/github-default-branch/bin/github-default-branch:64:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mheap** [comment]
Hey @jeffbyrnes! Looking at that it's a transient error from GitHub (`Server Error`).

Could you retry again and let me know if it happens again?

**Comment by jeffbyrnes** [comment]
And now it’s working! Nice. Thanks @mheap.
