### ISSUE TITLE
Error on repos w/o `README.md`

### ISSUE THREAD

**Issue by wooorm** [mheap/github-default-branch#25]
Hey, appreciate the project! Have been using it to update about 200 repos already and it’s working great!

The repos I maintain use `readme.md`, which since https://github.com/mheap/github-default-branch/commit/030c20800d233383229497bbc8592a8600d3f461, 1) doesn’t get updated, and 2) fail:

```
$ github-default-branch --verbose --confirm --repo vfile/ideas
You have 5000 API requests remaining

✏️  Processing vfile/ideas
✏️  Creating branch [main] at [8d408fcd73746c2e3069caaabafe6a529e626b5d]
✏️  Updating default branch to [main] in [ideas]
✏️  Changing branch protections
✏️  Deleting old branch [master] in ideas
RequestError [HttpError]: Not Found
    at /Users/tilde/.nvm/versions/node/v14.0.0/lib/node_modules/github-default-branch/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async loadFile (/Users/tilde/.nvm/versions/node/v14.0.0/lib/node_modules/github-default-branch/src/update-content.js:63:7)
    at async module.exports (/Users/tilde/.nvm/versions/node/v14.0.0/lib/node_modules/github-default-branch/src/update-content.js:27:18)
    at async /Users/tilde/.nvm/versions/node/v14.0.0/lib/node_modules/github-default-branch/bin/github-default-branch:168:5 {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 19 Jun 2020 08:24:04 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': '',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '8A25:460B2:6FB7171:867303B:5EEC7624',
    'x-oauth-scopes': 'admin:org, repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4993',
    'x-ratelimit-reset': '1592558640',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/vfile/ideas/contents/README.md',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.0 octokit-core.js/3.0.0 Node.js/14.0.0 (macOS Catalina; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/repos/contents/#get-contents'
}

✅ Complete
```

**Comment by mheap** [comment]
Hey @wooorm! Thanks for the report. Fortunately the error is only logged, and execution continues as planned.

I updated the error log in a3fe566 and it should look a lot more friendly now. Check out release 1.6.1 to see the changes

**Comment by wooorm** [comment]
Sweet!
